#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

foreach (qw(
    trusted-networks-modify
)) {
    event_templates($_, qw(/etc/httpd/conf.d/nethserver.conf));
    event_services($_, qw(httpd reload));
}

#
# nethserver-httpd-update event
#
event_templates('nethserver-httpd-update', qw(
		/etc/httpd/conf.d/nethserver.conf
                /etc/httpd/conf.d/default-virtualhost.inc
                /etc/httpd/conf.d/proxypass.conf
                /etc/httpd/conf.d/virtualhosts.conf
                /etc/pki/tls/certs/localhost.crt
                /etc/pki/tls/private/localhost.key
                /etc/httpd/conf.d/welcome.conf
));

event_actions('nethserver-httpd-update', qw(
	      initialize-default-databases 00
));

event_services('nethserver-httpd-update', qw(
               httpd restart
));


#
# certificate-update event
#
event_templates('certificate-update', qw(
                /etc/pki/tls/certs/localhost.crt
                /etc/pki/tls/private/localhost.key
                /etc/httpd/conf.d/nethserver.conf
));

event_services('certificate-update', qw(
               httpd reload
));


#
# migration-import event (refs #1690)
#
event_actions('migration-import', qw(
    nethserver-httpd-migrate 30
));

#
# nethserver-httpd-save event
#
event_templates('nethserver-httpd-save', qw(
    /etc/httpd/conf.d/proxypass.conf
    /etc/httpd/conf.d/virtualhosts.conf
));

event_services('nethserver-httpd-save', qw(
               httpd reload
));

#
# tls-policy-save event
#

event_templates('tls-policy-save', qw(
        /etc/httpd/conf.d/nethserver.conf
));

event_services('tls-policy-save', qw(
        httpd restart
));

