#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::Build::CreateLinks qw(:all);

foreach (qw(
    network-create 
    network-delete 
    remoteaccess-update 
    ibay-modify 
    ibay-create 
    ibay-delete
)) {
    event_templates($_, qw(/etc/httpd/conf/httpd.conf));
    event_services($_, qw(httpd reload));
}

# Set ibay password on ibay events:
foreach (qw(
    ibay-create
    ibay-delete
    ibay-modify
)) {
    event_actions($_, qw(nethserver-httpd-setibayspassword 30));
}

# Initialize the password database when ibays are installed/updated
event_actions('nethserver-ibays-update', qw(nethserver-httpd-setibayspassword 40));

#--------------------------------------------------
# actions for nethserver-httpd-update event
#--------------------------------------------------

event_templates('nethserver-httpd-update', qw(
		/etc/httpd/conf/httpd.conf
		/etc/httpd/conf.d/ssl.conf
));

event_actions('nethserver-httpd-update', qw(
	      initialize-default-databases 00
	      nethserver-httpd-conf 20
	      firewall-adjust 30
	      runlevel-adjust 30
));

event_services('nethserver-httpd-update', qw(
               httpd restart
));


#
# UNINSTALL event
#
event_actions('nethserver-httpd-uninstall', qw(
              nethserver-httpd-uninstall 00
              runlevel-adjust 30
              firewall-adjust 40
));
