#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

my $ret = {};


if ($cmd eq 'configuration') {

    my $db = esmith::ConfigDB->open_ro();
    $ret->{'configuration'}{'MaxExecutionTime'} = $db->get_prop('php', 'MaxExecutionTime') || '0';
    $ret->{'configuration'}{'MemoryLimit'} = $db->get_prop('php', 'MemoryLimit') || '128';
    $ret->{'configuration'}{'PostMaxSize'} = $db->get_prop('php', 'PostMaxSize')|| '8';
    $ret->{'configuration'}{'UploadMaxFilesize'} = $db->get_prop('php', 'UploadMaxFilesize')|| '4';

} else {
    error();
}

print encode_json($ret);
