#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;

my $event = shift;
my $ibayName = shift;

if( ! $event) {
    die("Missing event argument");
}

my @ibayList = ();

my $accountsDb = esmith::AccountsDB->open() or die("Could not open Accounts DB!");
my $errors = 0;

if( ! $ibayName) {
    @ibayList = $accountsDb->ibays();
} else {
    @ibayList = ($accountsDb->get($ibayName)) || ();
}

foreach my $ibay (@ibayList) {
    if($ibay->prop('type') ne 'ibay') {
	warn("[ERROR] Account record $ibayName is not of type ibay");
	$errors++;
	next;
    }
    
    my $httpStatus = $ibay->prop('HttpStatus') || '';
    my $aclList = $ibay->prop('AclList') || '';
    my @acls = split(',', $aclList);
    
    if($httpStatus eq 'enabled') {
	# Add ACL for apache user, if it's missing:
	if( ! grep /apache/, @acls) {
	    push @acls, 'u:apache:rX', 'd:u:apache:rX';
	}    
    } else {
	# Filter out apache ACLs:
	@acls = grep { $_ !~ m/apache/} @acls;
    }
    
    if($aclList ne join(',', @acls)) {
	$ibay->set_prop('AclList', join(',', @acls));
    }
}

exit($errors == 0 ? 0 : 1);
