#!/usr/bin/perl 

#
# nethserver-httpd-ibaypassword -- change the ibay password with htpasswd
#
# Copyright (C) 2012 Nethesis srl
#

use strict;

use esmith::AccountsDB;

my $ibayName = shift || die('Missing ibay name argument!');

my $passwordFile = '/etc/httpd/conf/ibays.htpasswd';
my $htpasswd = '/usr/bin/htpasswd';

my $db = esmith::AccountsDB->open_ro() || die('Could not open accounts database!');

if($db->get_prop($ibayName, 'type') ne 'ibay') {
    die("The given argument \"$ibayName\" is not an ibay account!");
}

if($db->get_prop($ibayName, 'HttpPasswordState') ne 'enabled') {
    exit 0;
}

if( ! -r $passwordFile ) {
    if( system($htpasswd, '-c', $passwordFile) != 0 ) {

    }
}

my $password = $db->get_prop($ibayName, 'HttpPasswordValue');

if($password) {
    my $action = (-r $passwordFile ? 'update' : 'create');
    if(system($htpasswd, 
	      '-bs' . ($action eq 'create' ? 'c' : ''), 
	      $passwordFile, 
	      $ibayName, 
	      $password) != 0) {
	die("Could not $action the htpasswd database file in " . $passwordFile);
    }
}

