#!/usr/bin/perl

use esmith::templates;
use esmith::ConfigDB;
my $vdb = esmith::ConfigDB->open_ro('vhosts') || die("Can't open vhosts db");
my $db = esmith::ConfigDB->open_ro('configuration') || die("Can't open config db");

my @outDir = ('/etc/opt/rh/rh-php71/php-fpm.d/',
             '/etc/opt/rh/rh-php72/php-fpm.d/',
         );

#We remove file before to recreate it
foreach my $outDir (@outDir){
unlink glob $outDir . 'php-fpm.*.conf';
}

foreach my $vhost ($vdb->get_all_by_prop('type'=>'vhost')) {

    my %vhostData = $vhost->props();


    $vhostData{VhostName} = $vhost->key;
    $vhostData{phpFpm} = $vdb->get_prop($vhost->key,'PhpRhVersion') || 'default';

    #skip if vhost status is not enabled
    if( !defined($vhostData{status}) || $vhostData{status} ne 'enabled' ){
        next;
    }
    #skip if vhost phpFpm is default
    if( !defined($vhostData{phpFpm}) || $vhostData{phpFpm} eq 'default' ){
        next;
    }

    #paths are different following the php version
    if ($vhostData{phpFpm} eq 'php71') {
        $path = "/etc/opt/rh/rh-php71/php-fpm.d/www.conf" if ($vhostData{phpFpm} eq 'php71');
        $out = "/etc/opt/rh/rh-php71/php-fpm.d/" if ($vhostData{phpFpm} eq 'php71');
    }
    elsif ($vhostData{phpFpm} eq 'php72') {
        $path = "/etc/opt/rh/rh-php72/php-fpm.d/www.conf" if ($vhostData{phpFpm} eq 'php72');
        $out = "/etc/opt/rh/rh-php72/php-fpm.d/" if ($vhostData{phpFpm} eq 'php72');
    }

    $OUT .= esmith::templates::processTemplate({
                    MORE_DATA => \%vhostData,
                    TEMPLATE_PATH => $path,
                    OUTPUT_TYPE => 'file',
                    OUTPUT_PREFIX => $out,
                    OUTPUT_FILENAME => 'php-fpm.'. $vhostData{VhostName}.'.conf'
     });
}
